<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>bamm</AssemblyName>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		<PublishSingleFile>true</PublishSingleFile>		
		<SelfContained>true</SelfContained>

		<Authors>Static-Codes</Authors>
		<Copyright>Copyright © Static-Codes</Copyright>
		<PackageTags>console;utility;windows;linux;osx</PackageTags>
		<Description>Custom scripting language and transpiler converting an english like language into valid Python code on Python &gt;= 3.9 </Description>
		
		<DebugType>embedded</DebugType>

		<!-- Default Runtime Identifier: Windows x64 (64 Bit) -->
		<RuntimeIdentifiers>win-x64;win-arm64;linux-x64;linux-arm64;osx-x64;osx-arm64;linux-arm</RuntimeIdentifiers>
		
	</PropertyGroup>

	<PropertyGroup>
		<!-- NuGet Package Metadata -->
		<PackAsTool>false</PackAsTool>
		<PackageId>bamm</PackageId>
		<PackageVersion>1.0.0-alpha8</PackageVersion>

		<!-- Windows & OSX License -->
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<ApplicationIcon>Resources/bamm.ico</ApplicationIcon>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	
	</PropertyGroup>
	
	<!-- Debian Packaging Properties -->
	<PropertyGroup>
		<CommonPackageName>$(PackageId)</CommonPackageName>
		<CommonPackageVersion>$(PackageVersion)</CommonPackageVersion>
		<CommonPackageSummary>Custom scripting language for Web Automation that compiles for Python</CommonPackageSummary>
		<CommonPackageLicense>MIT</CommonPackageLicense>
		<CommonDesktopName>BAM Manager (BAMM!)</CommonDesktopName>
		<RepositoryUrl>https://github.com/Static-Codes/BrowserAutomationMaster/</RepositoryUrl>
	</PropertyGroup>

	<!-- Debian Package Metadata-->
	<PropertyGroup Condition="'$(BuildDebPackage)' == 'true'">
		<DebianPackageMaintainer>$(Authors)</DebianPackageMaintainer>
		<DebianPackageDescription>$(Description)</DebianPackageDescription>
		<DebianPackageSection>utils</DebianPackageSection>
		<DebianPackagePriority>optional</DebianPackagePriority>
		<DebianPackageRequires>libicu-dev, python3, python3-venv, python3-dev, build-essential, xclip</DebianPackageRequires>
		<DebianDesktopFile>$(CommonPackageName).desktop</DebianDesktopFile>
		<DebianDesktopCategories>Utility;Console;</DebianDesktopCategories>
		<DebianDesktopTerminal>true</DebianDesktopTerminal>
		<DebianDesktopName>$(CommonDesktopName)</DebianDesktopName>
	</PropertyGroup>


	<!-- Fedora Package Metadata-->
	<PropertyGroup Condition="'$(BuildRpmPackage)' == 'true'">
		<RpmPackageName>$(CommonPackageName)</RpmPackageName>
		<RpmVersion>$(CommonPackageVersion)</RpmVersion>
		<RpmRelease>1</RpmRelease>
		<RpmSummary>$(CommonPackageSummary)</RpmSummary>
		<RpmLicense>$(CommonPackageLicense)</RpmLicense>
		<RpmUrl>$(RepositoryUrl)</RpmUrl>
		<RpmVendor>$(Authors)</RpmVendor>
		<RpmPackager>$(Authors)</RpmPackager>
		<RpmGroup>Applications/Utilities</RpmGroup>
		<!-- <RpmRequires>$(RpmRequires) libicu-dev, python3, python3-venv, python3-dev, build-essential, xclip</RpmRequires> -->
		<RpmDesktopFile>$(CommonPackageName).desktop</RpmDesktopFile>
		<RpmDesktopCategories>Utility;Console;Development;</RpmDesktopCategories>
		<RpmDesktopTerminal>true</RpmDesktopTerminal>
		<RpmDesktopName>$(CommonDesktopName)</RpmDesktopName>
	</PropertyGroup>

	<!-- macOS Specific Logic -->
	<PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64' Or '$(RuntimeIdentifier)' == 'osx-x64'">
		<TargetFramework>net10.0</TargetFramework>
		<PublishSingleFile>true</PublishSingleFile>
		<StripSymbols>false</StripSymbols>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	</PropertyGroup>

	<ItemGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64' Or '$(RuntimeIdentifier)' == 'osx-x64'">
		<EmbeddedResource Include="Resources/macOS/free" />
	</ItemGroup>
	<!-- End of macOS Specific Logic -->

	<!-- Download and Embed Logic-->
	<Target Name="RetrieveAndEmbedResources" BeforeTargets="PrepareForBuild">

		<!-- Erroring out if an unsupported Windows Build is found.-->
		<Error Condition="'$(IsSupportedWin10)' == 'false'" Text="Build Failure: Unsupported Windows 10 build version detected: $(WindowsBuildVersion)" />

		<Error Condition="'$(ResourceURL)' == ''" Text="Build Failure: ResourceURL property is empty." />

		<!-- Creating the DownloadDir, if it was removed for some reason. -->
		<MakeDir Directories="$(DownloadDir)" />

		<!-- Deleting a previously downloaded copy of the file if its present, to ensure it's the latest version. -->
		<Delete Files="$(_FullResourcePath)" Condition="Exists('$(_FullResourcePath)')" />

		<!-- Downloading the file located at the specified url, to the provided output path. -->
		<!-- Handle exit code 6, which means no network connection is present. -->
		<Exec Command="curl -fLs &quot;$(ResourceURL)&quot; -o &quot;$(_FullResourcePath)&quot;" StandardOutputImportance="low" IgnoreExitCode="true">
			
			<Output TaskParameter="ExitCode" PropertyName="CurlExitCode" />
		</Exec>
		
		<Error Condition="'$(CurlExitCode)' == '6'" Text="Please ensure you have an active network connection; curl could not resolve the host for $(ResourceURL)." />

		<Error Condition="'$(CurlExitCode)' != '0' AND '$(CurlExitCode)' != '6'" Text="Resource download failed with exit code: $(CurlExitCode)." />

		<ItemGroup>
			<EmbeddedResource Include="$(_FullResourcePath)" Watch="false" />
		</ItemGroup>
	</Target>

	<!-- Windows Version Check -->
	<!-- Due to BAMM support all versions of Windows 10 and 11 this check is required-->
	<!-- This check is  prior to April 2018 (build 10240) will fail as they do not support curl natively -->
	<Target Name="ValidateWindowsVersion" BeforeTargets="Build" Condition="$([MSBuild]::IsOSPlatform('Windows'))">
		<PropertyGroup>
      		<IsSupportedWin10>$([MSBuild]::VersionGreaterThanOrEquals($(WindowsBuildVersion), 10240))</IsSupportedWin10>
    	</PropertyGroup>
	</Target>

	<Target Name="RemoveGUIAfterEmbed" AfterTargets="Build">
      	<Delete Files="$(_FullResourcePath)" Condition="Exists('$(_FullResourcePath)')" />
	</Target>

	<!-- GUI.zip Download and Embed Logic -->
	<PropertyGroup>
		<ResourceURL>https://raw.githubusercontent.com/Static-Codes/BrowserAutomationMaster/refs/heads/gui/gui.zip</ResourceURL>
    	<DownloadDir>Resources</DownloadDir>
    	<DownloadedFileName>gui.zip</DownloadedFileName>
		<!-- MSBuild on Windows handles forward slashes as intended, but, Unix treats backslashes as literals rather than seperators -->
    	<_FullResourcePath>$(DownloadDir)/$(DownloadedFileName)</_FullResourcePath>
	</PropertyGroup>

	<!-- Embedded Resource Logic -->
	<ItemGroup>

		<!-- App Icon -->
		<EmbeddedResource Include="Resources/bamm.ico" />

		<EmbeddedResource Include="Resources/UIDaemon.py" />

		<!-- Precompiled Wheels -->
		<EmbeddedResource Include="Resources/wheels/*/*.whl" />
		<EmbeddedResource Include="Resources/userScripts/*.bamc" />
	</ItemGroup>

	<!-- Port of NativeFileDialogSharp by Milleniumbug for .NET 10  -->
	<!-- https://github.com/Static-Codes/NativeFileDialogSharp -->
	
	<ItemGroup>
		<Content Include="Resources/NativeFileDialog/runtimes/linux-x64/libnfd.so">
		<Link>libnfd.so</Link>
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		<Visible>false</Visible>
		</Content>
	
		<Content Include="Resources/NativeFileDialog/runtimes/osx-x64/libnfd.dylib">
		<Link>libnfd.dylib</Link>
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		<Visible>false</Visible>
		</Content>

		<Content Include="Resources/NativeFileDialog/runtimes/win-x64/nfd.dll">
		<Link>nfd.dll</Link>
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		<Visible>false</Visible>
		</Content>
	</ItemGroup>

	
	<!-- Esprima (JS Validation) + Packaging.Targets (Cross Platform Publishing) -->
	<ItemGroup>
		<PackageReference Include="Esprima" Version="3.0.5" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183">
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Packaging.Targets" Version="0.1.232">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Photino.NET" Version="4.0.16" />
		<PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
		<PackageReference Include="Spectre.Console" Version="0.50.0" />
		<PackageReference Include="TextCopy" Version="6.2.1" />
		<PackageReference Include="YamlDotNet" Version="16.3.0" />
	</ItemGroup>

	

</Project>