<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<!-- Core Properties -->
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AssemblyName>bamm</AssemblyName>

		<!-- Default Runtime Identifier: Windows x64 (64 Bit) -->
		<RuntimeIdentifiers>win-x64;win-arm64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>

		<!-- Global Publish Settings  -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
	</PropertyGroup>

	<PropertyGroup>
		<!-- NuGet Package Metadata -->
		<PackAsTool>false</PackAsTool>
		<PackageId>bamm</PackageId>
		<PackageVersion>1.0.0</PackageVersion>
		<Authors>Static</Authors>
		<Description>Domain Specific Language Compiler converting an english like language into valid Python code on Python &gt;= 3.X </Description>
		<Copyright>Copyright © Static</Copyright>
		<PackageTags>console;utility;windows;linux;osx</PackageTags>
		<!-- Windows & OSX License -->
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<ApplicationIcon>bamm.ico</ApplicationIcon>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	
	<!-- Debian Packaging Properties -->
	<PropertyGroup Condition="$(RuntimeIdentifier.StartsWith('linux'))">
		<DebianPackageMaintainer>Static</DebianPackageMaintainer>
		<DebianPackageDescription>$(Description)</DebianPackageDescription>
		<DebianPackageSection>utils</DebianPackageSection>
		<DebianPackagePriority>optional</DebianPackagePriority>
		<DebianPackageRequires>libicu-dev</DebianPackageRequires>
		<DebianDesktopFile>$(PackageId).desktop</DebianDesktopFile>
		<DebianDesktopCategories>Utility;Console;</DebianDesktopCategories>
		<DebianDesktopTerminal>true</DebianDesktopTerminal>
		<DebianDesktopName>BAM Manager 1.0.0A2</DebianDesktopName>
	</PropertyGroup>
	<ItemGroup>
	  <Content Include="bamm.ico" />
	</ItemGroup>

	
	<!-- Esprima (JS Validation) + Packaging.Targets (Cross Platform Publishing) -->
	<ItemGroup>
		<PackageReference Include="Esprima" Version="3.0.5" />
		<PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183">
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Packaging.Targets" Version="0.1.232">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
	</ItemGroup>


</Project>