#!/bin/bash
# Guard Clause Testing for the BAMM for Linux installer.
#
# Located at: src/Installers/Linux/install.sh
#
# The installer script runs before BAMM exists on the machine, so it cannot be covered by the XUnit suite. 
#
# These are the only automated checks it has.
#
# Package Managers and Release Lookup Tables are cached/stubbed, therefore, no network access is required nor sudo.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALLER="$SCRIPT_DIR/install.sh"
STUB_DIR="$(mktemp -d)"

# The generated package-format map, which is the only artifact that remains a data file. 
# It MUST be machine readable
TESTDATA="$SCRIPT_DIR/testdata"

# This markdown file contains a record of the distros that BAMM supports, along with gaps in coverage. 
GAPS_DOC="$SCRIPT_DIR/../../../sections/known-distribution-gaps.md"

PASS=0
FAIL=0

cleanup() { rm -rf "$STUB_DIR"; }
trap cleanup EXIT

fail() {
    printf '  \033[31mFAIL\033[0m  %s\n' "$1"
    [ $# -gt 1 ] && printf '        %s\n' "$2"
    FAIL=$((FAIL + 1))
}

pass() {
    printf '  ok    %s\n' "$1"
    PASS=$((PASS + 1))
}

assert_eq() {
    local label="$1" expected="$2" actual="$3"
    if [ "$actual" = "$expected" ]; then
        pass "$label"
    else
        fail "$label" "expected [$expected] got [$actual]"
    fi
}

printf '\n== Syntax ==\n'
if bash -n "$INSTALLER"; then
    pass "install.sh parses"
else
    fail "install.sh parses"
    printf '\nAborting: the script does not parse.\n'
    exit 1
fi

# Every function and constant the guards use must be defined before the first call to it.
check_defined_before_use() {
    local symbol="$1" description="$2"
    local definition first_call

    definition=$(grep -n "^${symbol}() {\|^${symbol}=" "$INSTALLER" | head -n 1 | cut -d: -f1)
    first_call=$(grep -n "${symbol}" "$INSTALLER" \
        | grep -v "^[0-9]*:${symbol}() {\|^[0-9]*:${symbol}=" \
        | grep -v "^\s*#" \
        | head -n 1 | cut -d: -f1)

    if [ -z "$definition" ]; then
        fail "$description" "$symbol is never defined"
        return
    fi

    if [ -z "$first_call" ]; then
        pass "$description"
        return
    fi

    if [ "$definition" -lt "$first_call" ]; then
        pass "$description"
    else
        fail "$description" "$symbol is used at line $first_call but defined at line $definition"
    fi
}

# The three guards at the top of the installer all call show_error_and_exit.
check_defined_before_use show_error_and_exit "show_error_and_exit is defined before the guards that use it"
check_defined_before_use show_warning "show_warning is defined before the map resolver that uses it"
check_defined_before_use show_info "show_info is defined before the map fetcher that uses it"
check_defined_before_use BUG_REPORT_LINK "BUG_REPORT_LINK is defined before the guards that use it"
check_defined_before_use PACKAGE_FORMATS_FILE "PACKAGE_FORMATS_FILE is defined before the fetcher that uses it"

# A call to an undefined function is a silent failure in a curl|bash installer, because the exit
# status is the failure and the message is not. Every helper must therefore exist somewhere.
for helper in show_error_and_exit show_warning show_info get_latest_release download_release \
              lookup_distro_in_map resolve_package_format fetch_package_formats; do
    if grep -q "^${helper}() {" "$INSTALLER"; then
        pass "helper $helper is defined"
    else
        fail "helper $helper is defined"
    fi
done

# The mapping generated by the BAMM Publisher. 
# Ensure it is regenerated alongside the note in the testdata README if the schema changes.
MAP="$TESTDATA/package-formats.json"

if [ ! -f "$MAP" ]; then
    fail "test data map exists" "$MAP not found"
    exit 1
fi

# Parses the BAMM for Linux installer for lookup_distro_in_map() and resolve_package_format()
# These functions are used in this test suite to avoid additional overhead associated with maintaining two sources of truth.
show_warning() { echo "[WARNING]: $1" >&2; }
show_info()    { echo "[INFO]: $1" >&2; }
DEBIAN_DISTROS=("debian" "ubuntu" "pop" "linuxmint" "kali" "raspbian" "elementary" "zorin" "parrot")
FEDORA_DISTROS=("fedora" "centos" "rhel" "almalinux" "rocky" "ol")

eval "$(sed -n '/^lookup_distro_in_map()/,/^}/p' "$INSTALLER")"
eval "$(sed -n '/^resolve_package_format()/,/^}/p' "$INSTALLER")"

if ! declare -f lookup_distro_in_map > /dev/null; then
    fail "installer still defines lookup_distro_in_map" "the sed extraction found nothing"
    exit 1
fi

printf '\n== Map lookup ==\n'

# Formats BAMM publishes and installs today.
for entry in \
    "ubuntu deb" "debian deb" "raspbian deb" "elementary deb" "zorin deb" \
    "parrot deb" "pop deb" "linuxmint deb" "kali deb" "deepin deb" "devuan deb" \
    "fedora rpm" "centos rpm" "rhel rpm" "almalinux rpm" "rocky rpm" "ol rpm" \
    "amzn rpm" "pclinuxos rpm" "altlinux rpm" "opensuse-leap rpm" "opensuse-tumbleweed rpm"
do
    set -- $entry
    PACKAGE_FORMATS_PATH="$MAP"
    assert_eq "lookup $1" "$2" "$(lookup_distro_in_map "$1")"
done

# Published formats that are not deb or rpm. 
# The installer refuses these with a specific message rather than claiming the distribution is unknown.
PACKAGE_FORMATS_PATH="$MAP"
assert_eq "lookup arch"       "pkg.tar.xz" "$(lookup_distro_in_map arch)"
assert_eq "lookup gentoo"     "tbz2"       "$(lookup_distro_in_map gentoo)"

# Formats BAMM recognize but have no build targets for. 
# These must be null, not a nominal extension; 
# Claiming BAMM publishes an .apk or a .pkg would send a user after a file that does not exist. 
# Void is .xbps, Alpine is .apk, Solus is .eopkg, and the BSDs are .pkg.
assert_eq "lookup alpine (no apk build)"  "null" "$(lookup_distro_in_map alpine)"
assert_eq "lookup void (no xbps build)"   "null" "$(lookup_distro_in_map void)"
assert_eq "lookup solus (no eopkg build)" "null" "$(lookup_distro_in_map solus)"
assert_eq "lookup freebsd (no pkg build)" "null" "$(lookup_distro_in_map freebsd)"
assert_eq "lookup openwrt (no ipk build)" "null" "$(lookup_distro_in_map openwrt)"
assert_eq "lookup slackware (no txz build)" "null" "$(lookup_distro_in_map slackware)"

# A null format means WhichDistroSharp reported no package manager, which is distinct from the distro being unknown.
assert_eq "lookup coreos (null)" "null" "$(lookup_distro_in_map coreos)"
assert_eq "lookup nixos (null)"  "null" "$(lookup_distro_in_map nixos)"

# Absent keys must return nothing, not a partial or case-insensitive match.
assert_eq "lookup absent key"       ""     "$(lookup_distro_in_map notarealdistro)"
assert_eq "lookup is not a prefix"   ""     "$(lookup_distro_in_map ubuntu-extra)"

# These are top level keys in the file but live outside the "distros" object, so a lookup that scanned the whole document would wrongly match them.
assert_eq "lookup ignores schema"        "" "$(lookup_distro_in_map schema)"
assert_eq "lookup ignores generatedFor"  "" "$(lookup_distro_in_map generatedFor)"

printf '\n== Format resolution ==\n'

resolve() {
    DISTRO_NAME="$1"
    PACKAGE_FORMATS_PATH="$2"
    resolve_package_format 2>/dev/null
}

# Default resolution logic used when an active network connection is present.
# Uses the map mentioned above.
assert_eq "resolves ubuntu from map"  "deb"           "$(resolve ubuntu "$MAP")"
assert_eq "resolves ol from map"      "rpm"           "$(resolve ol "$MAP")"
assert_eq "resolves pclinuxos to rpm" "rpm"           "$(resolve pclinuxos "$MAP")"
assert_eq "resolves arch format"      "pkg.tar.xz"    "$(resolve arch "$MAP")"
assert_eq "null format is NOT_SUPPORTED" "NOT_SUPPORTED" "$(resolve coreos "$MAP")"

# Fallback resolution logic that uses a built-in list to resolve distros supported by BAMM.
# This is the logic that runs when a network connection is not present.
# A release that failed to publish a map must not break installations that work today.
for entry in \
    "ubuntu deb" "debian deb" "pop deb" "linuxmint deb" "kali deb" "raspbian deb" \
    "elementary deb" "zorin deb" "parrot deb" \
    "fedora rpm" "centos rpm" "rhel rpm" "almalinux rpm" "rocky rpm" "ol rpm"
do
    set -- $entry
    assert_eq "fallback resolves $1" "$2" "$(resolve "$1" "")"
done

# A distro in neither source.
assert_eq "unknown distro resolves empty" "" "$(resolve plan9 "$MAP")"
assert_eq "unknown distro offline resolves empty" "" "$(resolve plan9 "")"

# Every distro the built-in list names must also be in the map, with the same format.
# Otherwise removing the list in a later change would silently drop coverage. This is the check
# that makes that removal safe to do deliberately.
printf '\n== The map agrees with the built in list ==\n'
for entry in "${DEBIAN_DISTROS[@]}"; do
    assert_eq "map covers list entry $entry" "deb" "$(resolve "$entry" "$MAP")"
done
for entry in "${FEDORA_DISTROS[@]}"; do
    assert_eq "map covers list entry $entry" "rpm" "$(resolve "$entry" "$MAP")"
done

# The map must be larger than the 15 the lists name, or it is not buying any coverage.
entry_count=$(grep -cE '^\s{4}"' "$MAP")
if [ "$entry_count" -gt 15 ]; then
    pass "map covers more distros than the built in list ($entry_count > 15)"
else
    fail "map covers more distros than the built in list" "only $entry_count entries"
fi

# The map must record a null rather than omitting the key, because absence is indistinguishable
# from an incomplete map.
if grep -qE '"coreos": null' "$MAP"; then
    pass "map records null rather than omitting the key"
else
    fail "map records null rather than omitting the key"
fi

# Every value must be either a quoted string or an explicit null, never a bare token.
if grep -E '^\s{4}"' "$MAP" | grep -qvE '^\s{4}"[^"]+": ("[^"]*"|null),?$'; then
    fail "every map value is a string or null"
else
    pass "every map value is a string or null"
fi

# Only the formats BAMM actually publishes may appear as a value. This is the property that keeps
# the map honest: a nominal extension for a format with no build target would send a user after a
# release asset that does not exist. Mirrors PackageArtifactFormats, which is the generator.
PUBLISHED_FORMATS='deb|rpm|pkg\.tar\.xz|tbz2'
if grep -E '^\s{4}"' "$MAP" | grep -Eo ': "[^"]*"' | grep -qvE ": \"($PUBLISHED_FORMATS)\"$"; then
    fail "the map contains only formats BAMM publishes"
    grep -E '^\s{4}"' "$MAP" | grep -Eo '"[^"]*": "[^"]*"' | grep -vE ": \"($PUBLISHED_FORMATS)\"$" >&2
else
    pass "the map contains only formats BAMM publishes"
fi

# The map must be no larger than the publisher's package targets, and a distribution it cannot
# install for must be null rather than absent.
for id in alpine void solus freebsd; do
    if grep -qE "\"$id\": null" "$MAP"; then
        pass "$id is mapped to null, not omitted"
    else
        fail "$id is mapped to null, not omitted"
    fi
done

# The schema is pinned so the installer and the generator cannot disagree silently.
if grep -q '"schema": 1' "$MAP"; then
    pass "map schema is 1"
else
    fail "map schema is 1" "the generator or the schema version changed"
fi

printf '\n== Asset naming ==\n'

# These values must match real release assets.
# Failure to do so will result in a returned 404 status code.
# The release names are placed in the project's documentation for ease of access and improved maintainability.
RELEASE_VERSION="1.0.0-alpha7"   # v1.0.0A7
declare -A ARCH=([x86_64]=x64 [armv7l]=arm [aarch64]=arm64)

# grep rather than a sed substitution for the markers: 
# '<!--' inside an s/// expression is read as the start of a sed comment, which truncates the command and fails.
ASSETS=$(sed -n '/BEGIN PUBLISHED ASSETS/,/END PUBLISHED ASSETS/p' "$GAPS_DOC" \
    | grep -v -- '--' | grep -v '^\x60\x60\x60' | sed 's/^[[:space:]]*//' | grep -v '^$')

if [ -z "$ASSETS" ]; then
    fail "published asset names are readable from $GAPS_DOC"
else
    pass "published asset names are readable from $GAPS_DOC"
fi

for cpu in x86_64 armv7l aarch64; do
    for fmt in deb rpm; do
        name="bamm.$RELEASE_VERSION.linux-${ARCH[$cpu]}.$fmt"
        if printf '%s\n' "$ASSETS" | grep -qx "$name"; then
            pass "asset name $name exists in a real release"
        else
            fail "asset name $name exists in a real release"
        fi
    done
done

printf '\n== Download and install semantics ==\n'

# Asserting on the installer's source rather than running it. Running the script needs a package
# manager and root, and both of these are properties of the command lines, so reading them is
# enough and does not depend on the host.
grab() {
    grep -n -- "$1" "$INSTALLER" | head -n 1 | cut -d: -f1
}

# wget writes to "$1.1" when the target already exists instead of overwriting. The temporary
# directory is only removed on success, so a file from a failed run is there on the next one, and
# the stale package would be installed instead of the new one. -O forces the name and truncates.
if grep -q 'wget -O "\$2" "\$1"' "$INSTALLER"; then
    pass "download_release forces the output filename with wget -O"
else
    fail "download_release forces the output filename with wget -O" \
         "wget derives the name from the URL and saves to <name>.1 when the file exists, so a package left by a failed run gets installed"
fi

# dpkg is retried after apt-get -f. apt-get exits 0 when there was nothing to repair, so a corrupt
# package would otherwise be reported as a successful install.
if grep -q 'sudo apt-get install -f -y && sudo dpkg -i' "$INSTALLER"; then
    pass "dpkg is retried after the apt-get dependency repair"
else
    fail "dpkg is retried after the apt-get dependency repair" \
         "apt-get -f exits 0 when there is nothing to repair, so a failed dpkg would be reported as a successful install"
fi

# The temporary directory is only removed on success, which is what leaves the stale package behind.
# If that ever changes, the -O above becomes belt and braces rather than the only guard.
if grep -q 'rm -rf "\$TEMP_INSTALL_PATH" || show_warning' "$INSTALLER"; then
    pass "the temporary directory survives a failed run, which is why -O is required"
else
    pass "the temporary directory is removed before the install, or the download is unconditional"
fi

# Every failure has to be reported. A path that can reach the success message without the package
# manager succeeding is a silent failure.
if [ "$(grab 'Successfully installed latest release')" -gt "$(grep -n 'sudo dpkg -i "\$FILENAME" \\' "$INSTALLER" | tail -n 1 | cut -d: -f1)" ]; then
    pass "the success message is only reachable after the install commands"
else
    fail "the success message is only reachable after the install commands"
fi

printf '\n== Result ==\n'
printf '  passed: %d\n  failed: %d\n\n' "$PASS" "$FAIL"

[ "$FAIL" -eq 0 ] || exit 1
