# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
      
    - name: Clone repo
      run: cd $HOME && git clone https://github.com/Static-Codes/BrowserAutomationMaster.git

    # - name: Navigate to src directory
    #   run: cd $HOME/BrowserAutomationMaster/src
      
    - name: Restore dependencies
      run: cd $HOME/BrowserAutomationMaster/src && dotnet restore
      
    - name: Build
      run: cd $HOME/BrowserAutomationMaster/src && dotnet build --no-restore
      
    - name: Test
      run: cd $HOME/BrowserAutomationMaster/src && dotnet test --verbosity normal --no-build
 
